# Generated by Django 4.1.7 on 2023-02-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('kiszereles', models.CharField(max_length=5)),
                ('bevezetes_datuma', models.DateTimeField())
            ],
        ),
    ]
